### ISSUE TITLE
Path syntax

### ISSUE THREAD

**Issue by mellowism** [myntath/gtasks-ha#2]
I had this (awesome) component working up until a couple of days ago, and now I can’t get it set up again. I can’t remember what the paths were and after trying to set it up fresh I believe it is there it stops for me.
I have a path to credentials as follows:
/config/custom_components/gtasks/credentials/credentials.json
and in the setup of the integration, I’ve tried many different paths. Some give “Couldn’t find credentials” and some give “Unknown error”.
From logs: [Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packa - Pastebin.com 1](https://pastebin.com/nmE4f5Qm)
Any help is much appreciated.

## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by myntath** [comment]
Copying my reply from the home assistant forum:

It appears as if details are being loaded from the ‘token.pickle’ file rather than the credentials.json. Have you tried deleting the token.pickle file? Otherwise you could just change the writable path.

If you get your ‘Unknown Error’ then you credentials path is right and there is no need to change that.

Do you ever get through to the stage where you get a URL to click so you can copy the authorisation code?

If you still get an error after deleting the token.pickle file please provide a paste of that as it may help narrow the issue.

I may make an update so that the token.pickle file is deleted if it fails to refresh the token. Otherwise it does seem you may get stuck at this point. New credentials.json are ignored while the component tries to keep refreshing from the previous token.

**Comment by myntath** [comment]
Without any further information I'm closing this one.
